---
kind: pipeline
name: book
  
steps:
  - name: test
    image: hrektts/mdbook
    commands:
      - cd docs/book
      - mdbook test

  - name: build
    image: hrektts/mdbook
    commands:
      - cd docs/book
      - mdbook build
    
  - name: publish
    image: plugins/gh-pages
    settings:
      pages_directory: docs/book/build
      username:
        from_secret: github_username
      password:
        from_secret: github_access_key
    when:
      event:
        - push
      branch:
        - master

trigger:
  branch:
    exclude:
      - feature/*

---
kind: pipeline
name: linux-build

steps:
  - name: build
    image: clux/muslrust:nightly-2019-11-24
    commands:
      - cargo build --release
      - mkdir -p build/lucky
      - mv target/x86_64-unknown-linux-musl/release/lucky build/lucky
      - cd build/
      - tar -czf lucky-linux-x86_64.tgz lucky

  # Publish pre-release to GitHub releases
  - name: publish-pre-release
    image: plugins/github-release
    depends_on:
      - build
    settings:
      title: pre-release
      api_key:
        from_secret: github_access_key
      files:
        - build/lucky-linux-x86_64.tgz
    when:
      ref:
        - refs/tags/pre-release

  # Publish release to GitHub releases
  - name: publish-release
    image: plugins/github-release
    depends_on:
      - build
    settings:
      api_key:
        from_secret: github_access_key
      files:
        - build/lucky-linux-x86_64.tgz
    when:
      ref:
        - refs/tags/v*

trigger:
  branch:
    exclude:
      - feature/*

---
kind: pipeline
name: windows-build

steps:
  - name: build
    image: rust:latest
    commands:
      - apt-get update
      - apt-get install -y gcc-mingw-w64-x86-64 zip
      # TODO: Remove unnecessary installs
      # - >
      #   apt-get install -y gcc gcc-mingw-w64 pkg-config openssl libasound2-dev
      #   cmake build-essential libfreetype6-dev libexpat1-dev
      #   libxcb-composite0-dev libssl-dev zip
      - rustup default nightly-2019-11-24
      - rustup target install x86_64-pc-windows-gnu
      # Patch Some MingW Libs. See https://github.com/rust-lang/rust/issues/47048#issuecomment-474118132
      - cp -f /usr/x86_64-w64-mingw32/lib/dllcrt2.o /usr/local/rustup/toolchains/nightly-2019-11-24-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/dllcrt2.o
      - cp -f /usr/x86_64-w64-mingw32/lib/crt2.o /usr/local/rustup/toolchains/nightly-2019-11-24-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/crt2.o
      - mkdir -p .cargo
      - |
        echo '[target.x86_64-pc-windows-gnu]
        linker = "x86_64-w64-mingw32-gcc"' >> .cargo/config
      - cargo build --target x86_64-pc-windows-gnu --release
      - mkdir -p build/lucky
      - mv target/x86_64-pc-windows-gnu/release/lucky.exe build/lucky
      - cd build/
      - zip -r lucky-windows-x86_64.zip lucky

  # Publish pre-release to GitHub releases
  - name: publish-pre-release
    image: plugins/github-release
    depends_on:
      - build
    settings:
      title: pre-release
      api_key:
        from_secret: github_access_key
      files:
        - build/lucky-windows-x86_64.zip
    when:
      ref:
        - refs/tags/pre-release

  # Publish release to GitHub releases
  - name: publish-release
    image: plugins/github-release
    depends_on:
      - build
    settings:
      api_key:
        from_secret: github_access_key
      files:
        - build/lucky-windows-x86_64.zip
    when:
      ref:
        - refs/tags/v*

trigger:
  branch:
    exclude:
      - feature/*

---
kind: pipeline
name: macos-build

steps:
  - name: build
    image: rust:latest
    commands:
      # Install Cross-compiler toolchain
      - apt-get update
      - apt-get install -y clang cmake cpio make libssl-dev lzma-dev libxml2-dev
      - rustup default nightly-2019-11-24
      - rustup target add x86_64-apple-darwin
      - mkdir -p /build
      - cd /build
      - git clone --depth 1 https://github.com/tpoechtrager/osxcross.git
      - cd /build/osxcross/tarballs
      - wget https://s3.dockerproject.org/darwin/v2/MacOSX10.11.sdk.tar.xz
      - cd /build/osxcross
      - UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
      - export PATH="$PATH:/build/osxcross/target/bin"
      - ln -s /build/osxcross/target/SDK/MacOSX10.11.sdk/System/ /System
      # Configure build to use Mac linker and libraries
      - mkdir -p /drone/src/.cargo
      - |
        echo '[target.x86_64-apple-darwin]
        linker = "x86_64-apple-darwin15-clang"' >> /drone/src/.cargo/config
      - cd /drone/src
      - export COREAUDIO_FRAMEWORKS_PATH='/System/Library/Frameworks'
      - export CC=x86_64-apple-darwin15-clang
      - cargo build --target x86_64-apple-darwin --release
      - mkdir -p build/lucky
      - mv target/x86_64-apple-darwin/release/lucky build/lucky
      - cd build/
      - tar -czf lucky-mac-x86_64.tgz lucky

  # Publish pre-release to GitHub releases
  - name: publish-pre-release
    image: plugins/github-release
    depends_on:
      - build
    settings:
      title: pre-release
      api_key:
        from_secret: github_access_key
      files:
        - build/lucky-mac-x86_64.tgz
    when:
      ref:
        - refs/tags/pre-release

  # Publish release to GitHub releases
  - name: publish-release
    image: plugins/github-release
    depends_on:
      - build
    settings:
      api_key:
        from_secret: github_access_key
      files:
        - build/lucky-mac-x86_64.tgz
    when:
      ref:
        - refs/tags/v*

trigger:
  branch:
    exclude:
      - feature/*