[package]
name = "lucky"
version = "0.1.0"
authors = ["zicklag <zicklag@katharostech.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
zip = { version = "0.5", features = ["bzip2"], default-features = false }
handlebars = "2.0"
serde = { version = "1.0", features = ["derive"] }
color-backtrace = { version = "0.2", optional = true }
# TODO: Maybe replace this dependency with a handmade one
rprompt = "1.0"
termimad = "0.7"
crossterm = "0.13"
atty = "0.2"
anyhow = "1.0"

[features]
default = ["color-backtrace"]

[build-dependencies]
zip = { version = "0.5", features = ["bzip2"], default-features = false }
walkdir = "2.2"