[book]
title = "Lucky - A charming framework for Juju"
authors = ["Katharos Technology LLC and contributors"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/katharostech/lucky"
git-repository-icon = "fa-github"

[build]
build-dir = "build"
