[book]
title = "Juju Container Framework ( Name Pending )"
authors = ["Katharos Technology LLC and contributors"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/katharostech/juju-container-framework"
git-repository-icon = "fa-github"

[build]
build-dir = "build"
